### ISSUE TITLE
Remove "minecraft:" prefix to allow for longer messages

### ISSUE THREAD

**Issue by Balint817** [jaxvanyang/tp-chat-cmd#13]
Title + in case something other than `minecraft:` is present (`modname:`), then simply do nothing

**Comment by jaxvanyang** [comment]
> Title + in case something other than `minecraft:` is present (`modname:`), then simply do nothing

Hi! I didn't know that the namespace can be omitted. You remind me that the `@s` in `tp @s x y z` can also be omitted.

But this kind of trick only increase the length a little. I will update for this. But if you have a very long description need, you can first send the clickable message for teleporting, and then send a regular message follows that.

**Comment by jaxvanyang** [comment]
@Balint817 This update has been published on Modrinth, hope you enjoy it. :wink:
